# Permalinks
permalink: pretty

# Setup
title: Ismael Toé
tagline: Web & Mobile Developer
url: http://ismaeltoe.github.io
#paginate: 1

author:
  name: Ismael Toé
  twitter: https://twitter.com/ismaeltoe
  email: ismael.toe@gmail.com
